; UAOS network configuration
; Mode: dhcp or static
dhcp

; Static configuration (used as fallback when dhcp fails,
; or as primary config when mode is set to static)
; address
10.0.2.15
; netmask
255.255.255.0
; gateway
10.0.2.2
; dns
8.8.8.8
