/* uaos_emu_registry.c — UAOS embedded Amiga binary registry
 *
 * Each binary to be embedded is declared here as an extern uint8_t array
 * (generated by the build script from the raw binary using objcopy/xxd).
 * UAOS_Emu_RunByName looks up the name and calls UAOS_Emu_LoadAndRun.
 *
 * To add a new binary:
 *   1. Place the Amiga Hunk binary in emulation/binaries/<Name>
 *   2. The build script converts it to emulation/binaries/<Name>_bin.c
 *      containing:  const uint8_t g_bin_<Name>[] = { ... };
 *                   const uint32_t g_bin_<Name>_size = ...;
 *   3. Add an entry to k_programs[] below.
 */

#include "uaos_emu.h"
#include <stdint.h>
#include <stddef.h>

/* =========================================================================
 * Embedded binary declarations
 * ========================================================================= */

/* Forward-declared — defined in generated binaries/<Name>_bin.c files.
 * The build script (build_iso.sh) auto-generates the extern declarations
 * and the k_programs[] table from whatever raw binaries are present in
 * emulation/binaries/ at build time, replacing the section below. */

/* =========================================================================
 * Program table
 *
 * NOTE: The entries below are placeholders.  build_iso.sh regenerates this
 * file's first 44 lines from the contents of emulation/binaries/ at build
 * time, producing real extern declarations and k_programs[] entries for
 * each embedded binary.  When no binaries are present the table is empty.
 * ========================================================================= */

typedef struct {
    const char    *name;
    const uint8_t *data;
    uint32_t       size;
} EmbeddedProgram;

static const EmbeddedProgram k_programs[] = {
    { NULL, NULL, 0 }
};

/* =========================================================================
 * String helpers (no libc)
 * ========================================================================= */

static int reg_streq(const char *a, const char *b)
{
    while (*a && *b && *a == *b) { a++; b++; }
    return *a == *b;
}

static int reg_strlen(const char *s) { int n=0; while(s[n]) n++; return n; }

/* =========================================================================
 * Shell print adapter
 *
 * uaos_m68k_glue uses a simple (const char*) callback.
 * The shell uses (void* shell, const char* line).
 * We use a pair of file-scope globals to bridge them during a run.
 * (Single-threaded bare-metal — no concurrency concern.)
 * ========================================================================= */

static void         *g_current_shell = NULL;
static UAOS_PrintFn  g_current_print  = NULL;

static void glue_print_adapter(const char *line)
{
    if (g_current_print && g_current_shell)
        g_current_print(g_current_shell, line);
}

/* Forward declaration from uaos_m68k_glue.c */
typedef void (*GluePrintFn)(const char *);
extern int UAOS_Emu_LoadAndRun_Internal(const uint8_t *binary, uint32_t bin_size,
                                         const char **argv, GluePrintFn print_fn);

/* =========================================================================
 * Public API
 * ========================================================================= */

int UAOS_Emu_RunByName(const char *cmdline, void *shell, UAOS_PrintFn print_fn)
{
    /* Parse name (first token) from cmdline */
    char name[64];
    int ni = 0;
    while (cmdline[ni] && cmdline[ni] != ' ' && ni < 63)
        { name[ni] = cmdline[ni]; ni++; }
    name[ni] = '\0';

    if (!ni) {
        if (print_fn) print_fn(shell, "run: no program name given");
        return -1;
    }

    /* Look up in registry */
    const EmbeddedProgram *prog = NULL;
    for (int i = 0; k_programs[i].name; i++) {
        if (reg_streq(k_programs[i].name, name)) {
            prog = &k_programs[i];
            break;
        }
    }

    if (!prog) {
        char msg[80];
        int mi = 0;
        const char *pre = "run: '";
        while (*pre && mi<79) msg[mi++]=*pre++;
        for (int j=0; name[j] && mi<79; j++) msg[mi++]=name[j];
        const char *suf = "' not found (binary not embedded)";
        while (*suf && mi<79) msg[mi++]=*suf++;
        msg[mi]='\0';
        if (print_fn) print_fn(shell, msg);
        return -1;
    }

    /* Build argv: tokenise the remainder into individual words */
    static char arg_store[256];
    static const char *argv[18];
    argv[0] = prog->name;
    int argc = 1;

    /* Copy remainder into mutable buffer and split on spaces */
    const char *src = cmdline + ni;
    while (*src == ' ') src++;
    int ai = 0;
    while (*src && ai < 254) { arg_store[ai++] = *src++; }
    arg_store[ai] = '\0';

    char *tok = arg_store;
    while (*tok && argc < 16) {
        /* Skip leading spaces */
        while (*tok == ' ') tok++;
        if (!*tok) break;
        argv[argc++] = tok;
        /* Advance to next space or end */
        while (*tok && *tok != ' ') tok++;
        if (*tok == ' ') *tok++ = '\0';
    }
    argv[argc] = NULL;

    /* Set up print adapter */
    g_current_shell = shell;
    g_current_print = print_fn;

    return UAOS_Emu_LoadAndRun_Internal(prog->data, prog->size,
                                         (const char **)argv, glue_print_adapter);
}

int UAOS_Emu_LoadAndRun(const uint8_t *binary, uint32_t bin_size,
                         const char **argv, void *shell, UAOS_PrintFn print_fn)
{
    g_current_shell = shell;
    g_current_print = print_fn;
    return UAOS_Emu_LoadAndRun_Internal(binary, bin_size, argv, glue_print_adapter);
}
