#!/usr/bin/env bash
# embed_binary.sh — Embed an Amiga Hunk binary into the UAOS kernel
#
# Usage:
#   ./scripts/embed_binary.sh <binary_path> [<name>]
#
# Example:
#   ./scripts/embed_binary.sh /path/to/Lha Lha
#
# This generates:
#   emulation/binaries/<Name>_bin.c    — C byte array
#   emulation/binaries/<Name>_bin.h    — extern declaration
#
# After running this, rebuild the ISO:
#   ./scripts/build_iso.sh --clean

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
BINARIES_DIR="${REPO_ROOT}/emulation/binaries"

if [ $# -lt 1 ]; then
    echo "Usage: $0 <binary_path> [<name>]"
    exit 1
fi

BINARY_PATH="$1"
if [ ! -f "${BINARY_PATH}" ]; then
    echo "Error: file not found: ${BINARY_PATH}"
    exit 1
fi

# Derive name from filename if not specified
if [ $# -ge 2 ]; then
    NAME="$2"
else
    NAME="$(basename "${BINARY_PATH}")"
fi

# Sanitise name for use as a C identifier
CNAME="${NAME//[^a-zA-Z0-9_]/_}"

OUT_C="${BINARIES_DIR}/${CNAME}_bin.c"
OUT_H="${BINARIES_DIR}/${CNAME}_bin.h"

SIZE=$(wc -c < "${BINARY_PATH}")

echo "Embedding '${NAME}' (${SIZE} bytes) as g_bin_${CNAME}..."

# Generate .c file using xxd -i output style but without libc deps
{
    echo "/* Auto-generated by embed_binary.sh — do not edit */"
    echo "#include <stdint.h>"
    echo ""
    echo "const uint8_t g_bin_${CNAME}[] = {"
    xxd -i < "${BINARY_PATH}" | sed 's/^  /    /'
    echo "};"
    echo ""
    echo "const uint32_t g_bin_${CNAME}_size = ${SIZE};"
} > "${OUT_C}"

# Generate .h file
{
    echo "/* Auto-generated by embed_binary.sh — do not edit */"
    echo "#ifndef UAOS_BIN_${CNAME^^}_H"
    echo "#define UAOS_BIN_${CNAME^^}_H"
    echo "#include <stdint.h>"
    echo "extern const uint8_t  g_bin_${CNAME}[];"
    echo "extern const uint32_t g_bin_${CNAME}_size;"
    echo "#endif"
} > "${OUT_H}"

echo "Generated:"
echo "  ${OUT_C}"
echo "  ${OUT_H}"
echo ""
echo "Now edit emulation/uaos_emu_registry.c to add an entry:"
echo "  extern const uint8_t  g_bin_${CNAME}[];"
echo "  extern const uint32_t g_bin_${CNAME}_size;"
echo "  { \"${NAME}\", g_bin_${CNAME}, <size> },"
echo ""
echo "Then add to build_iso.sh compile loop:"
echo "  \"\${REPO_ROOT}/emulation/binaries/${CNAME}_bin.c\" \\"
echo ""
echo "And add -DUAOS_HAS_BIN_${CNAME^^} to the emulation compile flags."
echo ""
echo "Rebuild with: ./scripts/build_iso.sh --clean"
