#!/usr/bin/env python3
"""gen_ta_roots.py — generate system/bearssl/ta_roots.c from a PEM CA bundle.

Each CA certificate becomes a BearSSL br_x509_trust_anchor:
  dn   = DER-encoded subject Name (the full X.500 TLV, included)
  pkey = RSA {n, e} or EC {curve-id, uncompressed point}

Requires: python3 + 'cryptography' package.  Usage:

    tools/gen_ta_roots.py /etc/ssl/certs/ca-certificates.crt \
        > system/bearssl/ta_roots.c

BearSSL EC curve IDs: secp256r1=23, secp384r1=24, secp521r1=25.
Non-RSA/EC keys and unknown curves are skipped with a stderr note.
"""
import sys

from cryptography import x509
from cryptography.hazmat.primitives.asymmetric import rsa, ec
from cryptography.hazmat.primitives.serialization import (
    Encoding, PublicFormat)
from cryptography.x509.oid import NameOID

EC_CURVE_IDS = {
    "secp256r1": 23,
    "secp384r1": 24,
    "secp521r1": 25,
}


def der_int(v: int) -> bytes:
    """DER INTEGER content bytes (unsigned, positive)."""
    b = v.to_bytes(max(1, (v.bit_length() + 7) // 8), "big")
    if b[0] & 0x80:
        b = b"\x00" + b
    return b


def load_pem_bundle(path):
    data = open(path, "rb").read()
    certs, block = [], b""
    for line in data.splitlines(keepends=True):
        block += line
        if b"END CERTIFICATE" in line:
            certs.append(x509.load_pem_x509_certificate(block))
            block = b""
    return certs


def main():
    bundle = sys.argv[1] if len(sys.argv) > 1 else \
        "/etc/ssl/certs/ca-certificates.crt"
    certs = load_pem_bundle(bundle)

    anchors = []          # (dn, keytype, payload)
    skipped = 0
    for cert in certs:
        dn = cert.subject.public_bytes()
        key = cert.public_key()
        name = cert.subject.rfc4514_string()
        if isinstance(key, rsa.RSAPublicKey):
            n = der_int(key.public_numbers().n)
            e = der_int(key.public_numbers().e)
            anchors.append((dn, "rsa", (n, e), name))
        elif isinstance(key, ec.EllipticCurvePublicKey):
            cid = EC_CURVE_IDS.get(key.curve.name)
            if cid is None:
                skipped += 1
                print(f"skip EC curve {key.curve.name}: {name}",
                      file=sys.stderr)
                continue
            q = key.public_bytes(Encoding.X962,
                                 PublicFormat.UncompressedPoint)
            anchors.append((dn, "ec", (cid, q), name))
        else:
            skipped += 1
            print(f"skip key type {type(key).__name__}: {name}",
                  file=sys.stderr)

    out = []
    out.append("/* ta_roots.c — GENERATED by tools/gen_ta_roots.py; do not edit. */")
    out.append("/* Trust anchors for the vendored BearSSL x509_minimal verifier.  */")
    out.append(f"/* Source bundle: {bundle} ({len(certs)} certs, "
               f"{skipped} skipped) */")
    out.append('#include "bearssl.h"')
    out.append("")

    decls = []
    for i, (dn, kt, payload, name) in enumerate(anchors):
        def emit(label, b):
            items = [f"0x{x:02x}" for x in b]
            lines = [", ".join(items[i:i + 16])
                     for i in range(0, len(items), 16)]
            out.append(f"static const unsigned char {label}[] = {{\n"
                       + ",\n".join(lines) + "\n};")
        emit(f"ta_{i}_dn", dn)
        if kt == "rsa":
            n, e = payload
            emit(f"ta_{i}_n", n)
            emit(f"ta_{i}_e", e)
            key = (f"{{ BR_KEYTYPE_RSA, {{ .rsa = {{ "
                   f"(unsigned char *)ta_{i}_n, sizeof ta_{i}_n, "
                   f"(unsigned char *)ta_{i}_e, sizeof ta_{i}_e }} }} }}")
        else:
            cid, q = payload
            emit(f"ta_{i}_q", q)
            key = (f"{{ BR_KEYTYPE_EC, {{ .ec = {{ {cid}, "
                   f"(unsigned char *)ta_{i}_q, sizeof ta_{i}_q }} }} }}")
        out.append(f"/* {i}: {name} */")
        decls.append(
            f"    {{ {{ (unsigned char *)ta_{i}_dn, sizeof ta_{i}_dn }},\n"
            f"      BR_X509_TA_CA, {key} }},")

    out.append("")
    out.append("const br_x509_trust_anchor uaos_ta_roots[] = {")
    out.extend(decls)
    out.append("};")
    out.append("const size_t uaos_ta_roots_num = "
               "sizeof uaos_ta_roots / sizeof uaos_ta_roots[0];")
    out.append("")
    sys.stdout.write("\n".join(out))
    print(f"emitted {len(anchors)} anchors ({skipped} skipped)",
          file=sys.stderr)


if __name__ == "__main__":
    main()
